[2024-08-11T03:35:44.858+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-11T03:35:44.878+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.download_dataset_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-08-11T03:35:44.895+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.download_dataset_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-08-11T03:35:44.896+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-11T03:35:44.998+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): download_dataset_task> on 2024-01-01 00:00:00+00:00
[2024-08-11T03:35:45.009+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=50) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-11T03:35:45.011+0000] {standard_task_runner.py:64} INFO - Started process 52 to run task
[2024-08-11T03:35:45.015+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'download_dataset_task', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/googleBigQuery.py', '--cfg-path', '/tmp/tmpph7bt1n3']
[2024-08-11T03:35:45.018+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask download_dataset_task
[2024-08-11T03:35:45.102+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.download_dataset_task scheduled__2024-01-01T00:00:00+00:00 [running]> on host 398299d1f2b6
[2024-08-11T03:35:45.484+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='download_dataset_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-08-11T03:35:45.485+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-11T03:35:45.521+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-11T03:35:45.521+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'curl -X POST -H "Content-Type: application/json" -d \'{"year": 2015}\' http://localhost:5000/download-data --output 2015.csv']
[2024-08-11T03:35:45.544+0000] {subprocess.py:86} INFO - Output:
[2024-08-11T03:35:45.559+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-08-11T03:35:45.561+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-08-11T03:35:45.563+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2024-08-11T03:35:45.564+0000] {subprocess.py:93} INFO - curl: (7) Failed to connect to localhost port 5000 after 3 ms: Couldn't connect to server
[2024-08-11T03:35:45.566+0000] {subprocess.py:97} INFO - Command exited with return code 7
[2024-08-11T03:35:45.567+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-11T03:35:45.580+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 7.
[2024-08-11T03:35:45.585+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=my_dag, task_id=download_dataset_task, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20240811T033544, end_date=20240811T033545
[2024-08-11T03:35:45.615+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 7.; 52)
[2024-08-11T03:35:45.638+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-11T03:35:45.666+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-11T03:35:45.678+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
